/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [order_id]
      ,[customer_id]
      ,[order_status]
      ,[order_date]
      ,[required_date]
      ,[shipped_date]
      ,[store_id]
      ,[staff_id]
  FROM [BikeStores].[sales].[orders]



/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [customer_id]
      ,[first_name]
      ,[last_name]
      ,[phone]
      ,[email]
      ,[street]
      ,[city]
      ,[state]
      ,[zip_code]
  FROM [BikeStores].[sales].[customers]



/*I WANT TO START BY ADDING THE FIRST NAME, LAST NAME, CITY, STATE.
AND THESE ARE FOUND ON THE SALES.CUSTOMER TABLE

AND THEN THE ORDER ID AND THE ORDER DATE
WHICH ARE ON THE SALES.ORDER TABLE*/





SELECT
       ORD.ORDER_ID,
       CONCAT(CUS.FIRST_NAME,' ', CUS.LAST_NAME),
       CUS.CITY,
       CUS.STATE,
       ORD.ORDER_DATE
FROM SALES.ORDERS ORD
JOIN SALES.CUSTOMERS CUS
ON ORD.CUSTOMER_ID = CUS.CUSTOMER_ID;





/*TO ALSO KNOW THE SALES VOLUME AND THE TOTAL REVENUE GENERATED WE WOULD HAVE TO ADD TWO SUM FUNCTIONS 
THE SALES VOLUME AND THE TOTAL REVENUE COLUMN ARE BOTH FOUND ON THE SALES.ORDER_ITEMS TABLE*/





SELECT
       ORD.ORDER_ID,
       CONCAT(CUS.FIRST_NAME,' ', CUS.LAST_NAME),
       CUS.CITY,
       CUS.STATE,
       ORD.ORDER_DATE,
	   SUM(ITE.QUANTITY) AS 'TOTAL_UNITS',
	   SUM(ITE.QUANTITY * ITE.LIST_PRICE) AS 'REVENUE'
FROM SALES.ORDERS ORD
JOIN SALES.CUSTOMERS CUS
ON ORD.CUSTOMER_ID = CUS.CUSTOMER_ID
JOIN SALES.ORDER_ITEMS ITE
ON ORD.ORDER_ID = ITE.ORDER_ID
GROUP BY
ORD.ORDER_ID,
       CONCAT(CUS.FIRST_NAME,' ', CUS.LAST_NAME),
       CUS.CITY,
       CUS.STATE,
       ORD.ORDER_DATE





/*ALSO WANT TO KNOW THE NAMES OF THE PRODUCTS THAT WERE PURCHASED
FOUND ON THE PRODUCTION.PRODUCTS TABLE

CATEGORY OF THE PRODUCTS PURCHASED
FOUND ON THE PRODUCTION.CATEGORIES TABLE*/





SELECT
       ORD.ORDER_ID,
       CONCAT(CUS.FIRST_NAME,' ', CUS.LAST_NAME) AS CUSTOMERS,
       CUS.CITY,
       CUS.STATE,
       ORD.ORDER_DATE,
	   SUM(ITE.QUANTITY) AS 'TOTAL_UNITS',
	   SUM(ITE.QUANTITY * ITE.LIST_PRICE) AS 'REVENUE',
	   PRO.PRODUCT_NAME,
	   CAT.CATEGORY_NAME
FROM SALES.ORDERS ORD
JOIN SALES.CUSTOMERS CUS
ON ORD.CUSTOMER_ID = CUS.CUSTOMER_ID
JOIN SALES.ORDER_ITEMS ITE
ON ORD.ORDER_ID = ITE.ORDER_ID
JOIN PRODUCTION.PRODUCTS PRO
ON ITE.PRODUCT_ID = PRO.PRODUCT_ID
JOIN PRODUCTION.CATEGORIES CAT
ON PRO.CATEGORY_ID = CAT.CATEGORY_ID
GROUP BY
ORD.ORDER_ID,
       CONCAT(CUS.FIRST_NAME,' ', CUS.LAST_NAME),
       CUS.CITY,
       CUS.STATE,
       ORD.ORDER_DATE,
	   PRO.PRODUCT_NAME,
	   CAT.CATEGORY_NAME





/*LASTLY, I WANT TO FIND OUT THE STORE LOCATION
WHICH CAN BE FOUND IN THE SALES.STORES TABLE

AS WELL AS THE SALES REP INVOLVED IN THE SALE
THIS CAN BE FOUND ON THE SALES.STAFF TABLE*/





SELECT
       ORD.ORDER_ID,
       CONCAT(CUS.FIRST_NAME,' ', CUS.LAST_NAME) AS CUSTOMERS,
       CUS.CITY,
       CUS.STATE,
       ORD.ORDER_DATE,
	   SUM(ITE.QUANTITY) AS 'TOTAL_UNITS',
	   SUM(ITE.QUANTITY * ITE.LIST_PRICE) AS 'REVENUE',
	   PRO.PRODUCT_NAME,
	   CAT.CATEGORY_NAME,
	   STO.STORE_NAME,
	   CONCAT(STA.FIRST_NAME, ' ', STA.LAST_NAME) AS 'SALES_REP'
FROM SALES.ORDERS ORD
JOIN SALES.CUSTOMERS CUS
ON ORD.CUSTOMER_ID = CUS.CUSTOMER_ID
JOIN SALES.ORDER_ITEMS ITE
ON ORD.ORDER_ID = ITE.ORDER_ID
JOIN PRODUCTION.PRODUCTS PRO
ON ITE.PRODUCT_ID = PRO.PRODUCT_ID
JOIN PRODUCTION.CATEGORIES CAT
ON PRO.CATEGORY_ID = CAT.CATEGORY_ID
JOIN SALES.STORES STO
ON ORD.STORE_ID = STO.STORE_ID
JOIN SALES.STAFFS STA
ON ORD.STAFF_ID = STA.STAFF_ID
GROUP BY
ORD.ORDER_ID,
       CONCAT(CUS.FIRST_NAME,' ', CUS.LAST_NAME),
       CUS.CITY,
       CUS.STATE,
       ORD.ORDER_DATE,
	   PRO.PRODUCT_NAME,
	   CAT.CATEGORY_NAME,
	   STO.STORE_NAME,
	   CONCAT(STA.FIRST_NAME, ' ', STA.LAST_NAME)













